
application: flaming-octo-archer
version: 1-0-a-1
api_version: 1
runtime: python27
threadsafe: true

handlers:

# Endpoints api
- url: /_ah/spi/.*
  script: server.application

# Main page
- url: /
  static_files: dist/index.html
  upload: dist/index.html

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
