application: watering-web-client

# Version 1.0 (Alpha 2)
version: 1-0-a-2
api_version: 1
runtime: python27
threadsafe: true


handlers:
# Endpoints api
- url: /_ah/spi/.*
  script: server.application
  secure: always

# Static website
- url: /
  static_files: app/index.html
  upload: app/index\.html
  secure: always
- url: /
  static_dir: app
  secure: always

libraries:
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
