application: watering-web-client

# Version 1.0 (Alpha 2)
version: 1-0-a-2
api_version: 1
runtime: python27
threadsafe: true


handlers:
# Endpoints api
- url: /_ah/spi/.*
  script: python.application

# Static website
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist

libraries:
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
